(cl:defpackage beginner_tutorials-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "SUBTWOINTS"
   "<SUBTWOINTS-REQUEST>"
   "SUBTWOINTS-REQUEST"
   "<SUBTWOINTS-RESPONSE>"
   "SUBTWOINTS-RESPONSE"
  ))

