// Generated by gencpp from file beginner_tutorials/SubTwoIntsResponse.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_SUBTWOINTSRESPONSE_H
#define BEGINNER_TUTORIALS_MESSAGE_SUBTWOINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct SubTwoIntsResponse_
{
  typedef SubTwoIntsResponse_<ContainerAllocator> Type;

  SubTwoIntsResponse_()
    : sub(0)  {
    }
  SubTwoIntsResponse_(const ContainerAllocator& _alloc)
    : sub(0)  {
  (void)_alloc;
    }



   typedef int64_t _sub_type;
  _sub_type sub;





  typedef boost::shared_ptr< ::beginner_tutorials::SubTwoIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::SubTwoIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SubTwoIntsResponse_

typedef ::beginner_tutorials::SubTwoIntsResponse_<std::allocator<void> > SubTwoIntsResponse;

typedef boost::shared_ptr< ::beginner_tutorials::SubTwoIntsResponse > SubTwoIntsResponsePtr;
typedef boost::shared_ptr< ::beginner_tutorials::SubTwoIntsResponse const> SubTwoIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::SubTwoIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::SubTwoIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/pedro/catkin_ws/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::SubTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::SubTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::SubTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::SubTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::SubTwoIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::SubTwoIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::SubTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f5a20f081f63696a93c70a6384724004";
  }

  static const char* value(const ::beginner_tutorials::SubTwoIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf5a20f081f63696aULL;
  static const uint64_t static_value2 = 0x93c70a6384724004ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::SubTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/SubTwoIntsResponse";
  }

  static const char* value(const ::beginner_tutorials::SubTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::SubTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sub\n\
\n\
";
  }

  static const char* value(const ::beginner_tutorials::SubTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::SubTwoIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sub);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SubTwoIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::SubTwoIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::SubTwoIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "sub: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sub);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_SUBTWOINTSRESPONSE_H
