// Generated by gencpp from file beginner_tutorials/SubTwoInts.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_SUBTWOINTS_H
#define BEGINNER_TUTORIALS_MESSAGE_SUBTWOINTS_H

#include <ros/service_traits.h>


#include <beginner_tutorials/SubTwoIntsRequest.h>
#include <beginner_tutorials/SubTwoIntsResponse.h>


namespace beginner_tutorials
{

struct SubTwoInts
{

typedef SubTwoIntsRequest Request;
typedef SubTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SubTwoInts
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::SubTwoInts > {
  static const char* value()
  {
    return "9eb98bb9850f1c1774cf3ff3d5ba1aec";
  }

  static const char* value(const ::beginner_tutorials::SubTwoInts&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::SubTwoInts > {
  static const char* value()
  {
    return "beginner_tutorials/SubTwoInts";
  }

  static const char* value(const ::beginner_tutorials::SubTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::SubTwoIntsRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::SubTwoInts > 
template<>
struct MD5Sum< ::beginner_tutorials::SubTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::SubTwoInts >::value();
  }
  static const char* value(const ::beginner_tutorials::SubTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::SubTwoIntsRequest> should match 
// service_traits::DataType< ::beginner_tutorials::SubTwoInts > 
template<>
struct DataType< ::beginner_tutorials::SubTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::SubTwoInts >::value();
  }
  static const char* value(const ::beginner_tutorials::SubTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::SubTwoIntsResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::SubTwoInts > 
template<>
struct MD5Sum< ::beginner_tutorials::SubTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::SubTwoInts >::value();
  }
  static const char* value(const ::beginner_tutorials::SubTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::SubTwoIntsResponse> should match 
// service_traits::DataType< ::beginner_tutorials::SubTwoInts > 
template<>
struct DataType< ::beginner_tutorials::SubTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::SubTwoInts >::value();
  }
  static const char* value(const ::beginner_tutorials::SubTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_SUBTWOINTS_H
